### ISSUE TITLE
activationEvents?

### ISSUE THREAD

**Issue by mark-hahn** [prrrnd/atom-git-projects#8]
Is there a reason there are no activationEvents?  There are a lot of requires and the load time is 470 ms, which is the slowest of my 40 or so packages.

**Comment by mark-hahn** [comment]
I'll assume you want me to just add this speedup to my PR.

**Comment by prrrnd** [comment]
I believe `activationEvents` have been renamed to `activationCommands`. The reason it is not implemented is because I thought that `git-projects` had to be loaded when opening Atom as it is the first thing I use to open any of my projects. If it improves the performances, and if you're willing to include this in your PR, then it can only be a good thing :+1:

**Comment by mark-hahn** [comment]
>  as it is the first thing I use to open any of my projects

It would not harm that usage.
