### ISSUE TITLE
Random improvements?

### ISSUE THREAD

**Issue by mark-hahn** [prrrnd/atom-git-projects#9]
When I see places where I could improve the existing code my OCD cries out to change it.  A few places could be sped up and some could just be improved a bit (like using path.join).  So far I've seen 3 or 4 places.  But this is not my package.  Should I ...

- Leave well-enough alone?
- Do a PR for each improvement?
- Do one PR for all improvements?
- Just throw it all in the PR for the cache?  We could still change back what you don't like.

I don't have much experience with PRs.  I don't want to step out of line.

**Comment by prrrnd** [comment]
It is totally fine with me if you decide to improve/change things. I'm actually glad you are willing to do so, and that's the power of open source after all :-) I'm open to any suggestions or changes as long as they improve things and keep the package easy to use.
I am aware that the performances could be greatly improved. I think the best way would be to make a PR for all the improvements, and one for the cache, so that we keep things separate without having too many PRs at the same time. Anyway, thanks for your interest in this project!

**Comment by mark-hahn** [comment]
>  Anyway, thanks for your interest in this project!

It's one I would have done if I had thought of it.  Where did you get the idea?

**Comment by mark-hahn** [comment]
I'm not going to do this.  I found one large improvement.
